EventSite/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using EventSite.Domain.Commands;
using EventSite.Domain.Infrastructure;
using EventSite.Domain.Model;
using EventSite.Domain.Queries;
using EventSite.Domain.WorkItems;
using EventSite.Infrastructure.Controllers;
using EventSite.Infrastructure.Data.Export;
using EventSite.Infrastructure.Filters;
using EventSite.Infrastructure.Helpers;

namespace EventSite.Controllers {
    [LoggedIn(Roles = Roles.Admin)]
    public class EventsController : BaseController {
        const int PageSizeForExport = 50;

        [HttpGet]
        public ActionResult Index() {
            var events = DocSession.Query<Event>();
            return View(events);
        }

        [HttpGet]
        public ActionResult Create() {
            return View("CreateOrUpdate", new CreateOrUpdateEvent());
        }

        [HttpPost]
        public ActionResult Index(CreateOrUpdateEvent input) {
            return Execute(input)
                .OnSuccess(x => RedirectToAction("Detail", new { eventSlug = Event.SlugFromId(x.Subject.Id) }))
                .OnFailure(x => View("CreateOrUpdate", input));
        }

        [HttpGet]
        public ActionResult Detail(string eventSlug) {
            var ev = DocSession.Load<Event>(Event.IdFrom(eventSlug));
            if(ev == null) {
                return NotFound();
            }

            return View("CreateOrUpdate", new CreateOrUpdateEvent {
                Slug = eventSlug,
                Event = ev
            });
        }

        [HttpGet]
        public FileResult ExportAttendees(string eventSlug) {
            var eventId = Event.IdFrom(eventSlug);
            return PerformExcelExport("attendees",
                pageNumber =>  new AttendeesForEvent(eventId, pageNumber, PageSizeForExport),
                new AttendeesExportColumnMappings());
        }

        [HttpGet]
        public FileResult ExportSponsors(string eventSlug) {
            var eventId = Event.IdFrom(eventSlug);
            return PerformExcelExport("sponsors",
                new SponsorsForEvent(eventId),
                new SponsorsExportColumnMappings());
        }

        private FileResult PerformExcelExport<T>(string rootFileName, Func<int, Query<Page<T>>> queryBuilder, IExportColumnMappings<T> columns) {
            var exportItems = GetExcelExportItems(rootFileName, columns);
            exportItems.FileBuilder.Build(queryBuilder, exportItems.Exporter);
            return File(exportItems.TempFileInfo.FullName, "application/xlsx", exportItems.TempFileInfo.Name);
        }

        private FileResult PerformExcelExport<T>(string rootFileName, Query<IEnumerable<T>> query, IExportColumnMappings<T> columns) {
            var exportItems = GetExcelExportItems(rootFileName, columns);
            exportItems.FileBuilder.Build(query, exportItems.Exporter);
            return File(exportItems.TempFileInfo.FullName, "application/xlsx", exportItems.TempFileInfo.Name);
        }

        private dynamic GetExcelExportItems<T>(string rootFileName, IExportColumnMappings<T> columns) {
            var tempFileInfo = BuildExcelExportTempPath(rootFileName);
            return new
            {
                TempFileInfo = tempFileInfo,
                Exporter = new ExcelExporter<T>(columns, new FileInfoTargetFile(tempFileInfo), Bus),
                FileBuilder = new ExcelFileBuilder(Bus)
            };
        }

        private FileInfo BuildExcelExportTempPath(string rootFileName) {
            var timeStampedFileName = string.Format("{0}_{1}.xlsx", rootFileName, DateTime.Now.ToString("yyyyMMddHHmmss"));
            return new FileInfo(Path.Combine(Server.MapPath("~/App_Data"), timeStampedFileName));
        }

        [HttpPost]
        public ActionResult Detail(string eventSlug, CreateOrUpdateEvent input) {
            input.Event.Id = Event.IdFrom(eventSlug);
            return Execute(input)
                .OnSuccess(x => RedirectToAction("Detail", new {eventSlug}))
                .OnFailure(x => View("CreateOrUpdate", input));
        }

        [HttpPost]
        public ActionResult MakeCurrent(string eventSlug) {
            return Execute(new MakeEventCurrent(Event.IdFrom(eventSlug)))
                .Always(x => RedirectToAction("Detail", new { eventSlug }));
        }
    }
}

EventSite/Controllers/LocationController.cs
using System.Web.Mvc;
using EventSite.Domain;
using EventSite.Domain.Model;
using EventSite.Infrastructure.Controllers;

namespace EventSite.Controllers {
    public class LocationController : BaseController {
        [HttpGet]
        public ActionResult Index(string eventSlug) {
            if(string.IsNullOrEmpty(eventSlug) && State.NoEventScheduled()) {
                return View("NoEventScheduled");
            }

            var ev = string.IsNullOrEmpty(eventSlug)
                ? State.CurrentEvent
                : DocSession.Load<Event>(Event.IdFrom(eventSlug));

            return View(ev);
        }
    }
}

EventSite/Controllers/SpeakersController.cs
using System.Web.Mvc;
using EventSite.Domain;
using EventSite.Domain.Model;
using EventSite.Domain.Queries;
using EventSite.Infrastructure.Controllers;
using EventSite.ViewModels.RegisteredUsers;

namespace EventSite.Controllers {
    public class SpeakersController : BaseController {
        [HttpGet]
        public ActionResult Index(string eventSlug = null, string speakerSlug = null, int page = 1) {
            if(string.IsNullOrEmpty(eventSlug) && State.NoEventScheduled()) {
                return View("NoEventScheduled");
            }

            var eventId = string.IsNullOrEmpty(eventSlug)
                ? State.CurrentEvent.Id
                : Event.IdFrom(eventSlug);

            var speakers = Bus.Query(new SpeakersForEvent(eventId, page));

            return View(new IndexOutput<Speaker>(speakers, speakerSlug, eventSlug));
        }
    }
}

EventSite/Controllers/SponsorsController.cs
using System.Web;
using System.Web.Mvc;
using EventSite.Domain;
using EventSite.Domain.Commands;
using EventSite.Domain.Model;
using EventSite.Domain.Queries;
using EventSite.Infrastructure;
using EventSite.Infrastructure.Controllers;
using EventSite.Infrastructure.Filters;

namespace EventSite.Controllers {
    public class SponsorsController : BaseController {
        readonly IImageStorage imageStorage;

        public SponsorsController(IImageStorage imageStorage) {
            this.imageStorage = imageStorage;
        }

        [HttpGet]
        public ActionResult Index(string eventSlug = null, SponsorStatus? status = null) {
            if(string.IsNullOrEmpty(eventSlug) && State.NoEventScheduled()) {
                return View("NoEventScheduled");
            }

            var eventId = string.IsNullOrEmpty(eventSlug)
                ? State.CurrentEvent.Id
                : Event.IdFrom(eventSlug);

            var statusFilter = status.HasValue ? new[] { status.Value } : GetDefaultSponsorStatusesForQuery();
            var sponsors = Bus.Query(new SponsorsForEvent(eventId, statusFilter));

            return View(sponsors);
        }

        [HttpGet]
        public ActionResult Info(string eventSlug) {
            return View();
        }

        private SponsorStatus[] GetDefaultSponsorStatusesForQuery() {
            return State.UserCanManageSponsors()
                ? new[] {SponsorStatus.Active, SponsorStatus.Inactive}
                : new[] {SponsorStatus.Active};
        }

        [HttpGet]
        [LoggedIn(Roles = Roles.ManageSponsors)]
        public ActionResult Create(string eventSlug) {
            return View("CreateOrUpdate", new CreateOrUpdateSponsor());
        }

        [HttpPost]
        [LoggedIn(Roles = Roles.ManageSponsors)]
        public ActionResult Index(string eventSlug, CreateOrUpdateSponsor input, HttpPostedFileBase file) {
            return Execute(input)
                .OnSuccess(x => {
                    if(file == null || file.ContentLength == 0) {
                        DisplayErrorMessage("You must provide an image.");
                        return View("CreateOrUpdate", input);
                    }

                    x.Subject.ImageSource = imageStorage.Store(file.FileName, file.InputStream);

                    return RedirectToAction("Detail", new {
                        eventSlug,
                        sponsorSlug = Sponsor.SlugFromId(x.Subject.Id)
                    });
                })
                .OnFailure(x => View("CreateOrUpdate", input));
        }

        [HttpGet]
        [LoggedIn(Roles = Roles.ManageSponsors)]
        public ActionResult Detail(string eventSlug, string sponsorSlug) {
            var sponsor = DocSession.Load<Sponsor>(Sponsor.IdFrom(eventSlug, sponsorSlug));
            if(sponsor == null) {
                return NotFound();
            }

            return View("CreateOrUpdate", new CreateOrUpdateSponsor {
                Sponsor = sponsor
            });
        }

        [HttpPost]
        [LoggedIn(Roles = Roles.ManageSponsors)]
        public ActionResult Detail(string eventSlug, string sponsorSlug, CreateOrUpdateSponsor input, HttpPostedFileBase file = null) {
            input.Sponsor.Id = Sponsor.IdFrom(eventSlug, sponsorSlug);
            return Execute(input)
                .OnSuccess(x => {
                    if(file != null && file.ContentLength > 0) {
                        imageStorage.Remove(x.Subject.ImageSource);
                        x.Subject.ImageSource = imageStorage.Store(file.FileName, file.InputStream);
                    }

                    return RedirectToAction("Detail", new {eventSlug, sponsorSlug});
                })
                .OnFailure(x => View("CreateOrUpdate", input));
        }
    }
}

EventSite/Views/Shared/Footer.cshtml
@using EventSite.Domain

<div id="footer" class="footer">
    <div class="container">
        <div class="row text-center">
            <p>
                <a href="https://www.facebook.com/Tallahassee-Code-Camp-175430389192507/?fref=ts" title="Facebook"><i class="fa fa-facebook fa-2x"></i></a>&nbsp;&nbsp;
                <a href="https://twitter.com/tallycodecamp" title="Twitter"><i class="fa fa-twitter fa-2x"></i></a>
            </p>
        </div>
        <div class="row text-center">
            <p>&copy; @DateTime.Now.Year - @State.Settings.Owner</p>
        </div>
        <div class="row text-center">
            <a href="@Url.RouteUrl("Contact")">Contact Us</a>
        </div>
    </div>
</div>
<!--  
    Commit @State.Settings.CommitId
    -->

EventSite/Views/Shared/NavBar.cshtml
@using EventSite.Domain
@using EventSite.Domain.Infrastructure
@using EventSite.Domain.Model
@using EventSite.Infrastructure
@{
    var siteTitle = State.EventScheduled()
        ? State.CurrentEvent.Name
        : State.Settings.Name;
}
<div class="navbar-wrapper">
    <div class="container" style="padding: 0">
        <div class="navbar-custom navbar navbar-default navbar-fixed-top">
            <div class="container-fluid less-padding" >
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index", "Home")" style="margin-left: 0">
                        <img src="~/Content/images/Code-Camp-Logo---One-Line---shortest.png" title="@siteTitle" />
                        @*<span>@siteTitle</span>*@
                    </a>
                </div>
                <div class="navbar-collapse collapse navbar-right">
                    <ul class="nav navbar-nav">
                        @if (!State.RunningInProduction())
                        {
                            <li >
                                <a>This is a development/test environment.</a>
                            </li>
                        }
                        <li><a href="@Url.Action("Index", "Location", new{eventSlug=State.CurrentEventSlug()})">Time &amp; Place</a></li>
                        <li><a href="@Url.Action("Index", "Sessions", new{eventSlug=State.CurrentEventSlug()})">Sessions</a></li>
                        <li><a href="@Url.Action("Index", "Speakers", new{eventSlug=State.CurrentEventSlug()})">Speakers</a></li>
                        <li><a href="@Url.Action("Index", "Attendees", new {eventSlug=State.CurrentEventSlug()})">Attendees</a></li>
                        <li><a href="@Url.Action("Index", "Sponsors", new{eventSlug=State.CurrentEventSlug()})">Sponsors</a></li>
                        
                        @if(State.UserIsLoggedIn()) {
                            <li class="btn-group">
                                <a href="#" class="avatar dropdown-toggle" data-toggle="dropdown">
                                    <img title="@State.User.Username" src="@Avatar.GetUrl(State.User.Email)">
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="@Url.Action("Index", "Account")"><span class="glyphicon glyphicon-home"></span> My Account</a>
                                    </li>
                                
                                    @if(State.RegistrationStatus == RegistrationStatus.NotRegistered) {
                                        <li>
                                            <a href="@Url.Action("Create", "Registration", new{eventSlug=State.CurrentEventSlug()})"><span class="glyphicon glyphicon-registration-mark"></span> Register</a>
                                        </li>
                                    }
                                
                                    @if(State.CanSubmitSessions()) {
                                        <li>
                                            <a href="@Url.Action("Create", "Sessions", new{eventSlug=State.CurrentEventSlug()})"><span class="glyphicon glyphicon-cloud-upload"></span> Submit Session</a>
                                        </li>
                                    }
                                
                                    @if(State.UserIsAdmin()) {
                                        <li class="divider"></li>
                                    
                                        <li>
                                            <a href="@Url.Action("Index", "Events")"><span class="glyphicon glyphicon-calendar"></span> Events</a>
                                        </li>    
                                        
                                        if(State.EventScheduled()) {
                                             <li>
                                                 <a href="@Url.Action("Create", "Sponsors", new { eventSlug=State.CurrentEventSlug() })">
                                                     <span class="glyphicon glyphicon-heart"></span> Add Sponsor
                                                 </a>
                                            </li>
                                         }
                                    }

                                    <li class="divider"></li>

                                    <li>
                                        <a href="@Url.Action("LogOut", "Account")"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
                                    </li>
                                </ul>
                            </li>
                        } else {
                            <li><a href="@Url.Action("Login", "Account")">Login/Register</a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

@if(Result != null) {
    <div class="container">
        @if(Result.Succeeded()) {
            <div class="alert alert-success fade in">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <span>@Result.Message</span>
            </div>
        } else {
            <div class="alert alert-danger fade in">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <span>@Result.Message</span>
                
                @if(Result.Details.Count > 0) {
                    <ul>
                        @foreach(var detail in Result.Details) {
                            <li>@detail.Description</li>
                        }
                    </ul>
                }
            </div>
        }  
    </div>
}

EventSite/Views/Shared/NoEventScheduled.cshtml
@{
    ViewInfo.Title = "No Event Scheduled";
}

<div class="jumbotron">
    <h2>There is no event currently scheduled.</h2>
    <p class="lead">Please check back later for news on future events.</p>
</div>

EventSite/Views/Shared/_DefaultLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("NavBar")
<div id="wrap">
    <div class="container">

        @RenderBody()

    </div>
</div>
@Html.Partial("Footer")

EventSite/Views/Shared/_HomeLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("NavBar")
@RenderBody()

EventSite/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using EventSite.Domain
@{
    var title = (ViewInfo.Title ?? string.Empty) + " | ";
    if(State.EventScheduled()) {
        title += State.CurrentEvent.Name;
    } else {
        title += State.Settings.Name;
    }
}
<!DOCTYPE html>
<html>
    <head>
        <title>@title</title>
        
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="format-detection" content="telephone=no"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        
        <link rel="apple-touch-startup-image" href="~/Content/images/ios-startup-image-landscape.png" media="(orientation:landscape)" />
        <link rel="apple-touch-startup-image" href="~/Content/images/ios-startup-image-portrait.png" media="(orientation:portrait)" />
        <link rel="apple-touch-icon" href="~/Content/images/icon.png"/>
        <link rel="icon" href="@Url.Content("~/content/favicon.ico")" />

        @Styles.Render("~/Content/styles/combined")
        @*<link href="~/Content/styles/site.css" rel="stylesheet" />*@
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="../../Scripts/html5shiv.min.js"></script>
          <script src="../../Scripts/respond.min.js"></script>
        <![endif]-->
        
        <script type="text/javascript">
            if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
                var msViewportStyle = document.createElement("style");
                var mq = "@@-ms-viewport{width:auto!important}";
                msViewportStyle.appendChild(document.createTextNode(mq));
                document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
            }
        </script>
    </head>
    <body>
        @RenderBody()
        @Scripts.Render("~/Scripts/combined")
    </body>
</html>